spring:
  application:
    name: Spring5
  profiles:
    active: dev
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 180000
      connection-timeout: 30000
      connection-test-query: select 1
      pool-name: My-HikariCP
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8088

